### ISSUE TITLE
is there a wpuf_update_profile hook?

### ISSUE THREAD

**Issue by iwillhappy1314** [tareq1988/WP-User-Frontend#53]
Hi:

I have read the document about [post action hook](http://docs.wedevs.com/docs/wp-user-frontend-pro/tutorials/using-action-hook-field/), the idea is geniues. I have tried add the custom field to the profile edit form, the custom field can show in frontend, but I can`t find a way to save the value to user meta.

is the anyway to do this? thanks a a lot!

**Comment by tareq1988** [comment]
When updating a profile from frontend, we fire this action hook.
```php
do_action( 'wpuf_update_profile', $user_id, $form_id, $form_settings );
```

When someone is registering via our form builder, we fire this one:
```php
do_action( 'wpuf_after_register', $user_id, $userdata, $form_id, $form_settings );
```

So you can save the user data by binding a function on these action hooks and process those meta by accessing `$_POST` variable.

**Comment by iwillhappy1314** [comment]
Thanks a lot, got it !
