### ISSUE TITLE
Does not redirect to payment page when user save the post as draft.

### ISSUE THREAD

**Issue by mahbubme** [tareq1988/WP-User-Frontend#73]
How to reproduce:

- I fill the form
- I click "save draft"
- I go to my dashboard
- I click on the Edit post and I go back to form page already filled
- Now I'm ready to pay for the post but the "submit" button do NOT bring me to the payment page.

Note: payment settings configured properly.

**Comment by sohelamin** [comment]
Fixed at ce1dc1e
