### ISSUE TITLE
CSS Class Name Not Working

### ISSUE THREAD

**Issue by kelseyurgorenci** [tareq1988/WP-User-Frontend#75]
I have added CSS class names to a variety of field types and none are appearing.
<img width="955" alt="screen shot 2017-01-25 at 12 32 54 pm" src="https://cloud.githubusercontent.com/assets/24653532/22301862/7c5c1f06-e2fa-11e6-9f54-e6025fd10a42.png">
<img width="1251" alt="screen shot 2017-01-25 at 12 33 11 pm" src="https://cloud.githubusercontent.com/assets/24653532/22301861/7c57c852-e2fa-11e6-91e3-1c3665ad6bc4.png">

**Comment by mahbubme** [comment]
@kelseyurgorenci If you add class to a field then it should add inside **li** element. Please check the following screenshots.

![screenshot-2](https://cloud.githubusercontent.com/assets/10685760/22321545/f00e4954-e3bf-11e6-8531-f12fc044287d.png)
![screenshot](https://cloud.githubusercontent.com/assets/10685760/22321549/f468856e-e3bf-11e6-84f6-0d888ff9662f.png)

Let me know if the issue still exist on your side.

**Comment by kelseyurgorenci** [comment]
As you will see in the screenshots I have left, that is precisely what I did. However, no class was applied to the li element, which is why I attached a screenshot of the Inspector as well.

**Comment by sohelamin** [comment]
@kelseyurgorenci The screenshots you've shared with us seems it is not created by our plugin.
Please make sure you've put the form's shortcode in correct page. And you will find there a form not the list item.

**Comment by tareq1988** [comment]
@kelseyurgorenci The CSS classes are applied on the form only, not in the rendered meta values.

**Comment by kelseyurgorenci** [comment]
Hmm, in response to the last two comments:

@sohelamin It _is_ your plugin - the screenshots provided are taken from wp-user-frontend

@tareq1988 As shown in the screenshots provided: the CSS classes are not applying to the form; as shown they should be applying to the <li> element and they are not...

**Comment by mahbubme** [comment]
@kelseyurgorenci The CSS classes will add with form field, not with output data. After creating a form, check the fields on the frontend. 
![1](https://cloud.githubusercontent.com/assets/10685760/22412887/1a1d2164-e6dd-11e6-9613-d484043cc642.png)

**Comment by kelseyurgorenci** [comment]
I am not understanding why this is confusing. Please look at the screenshots I provided. They are of the Inspector on the frontend; as you will see there are NO classes created on the <li> element (which of course is showing the frontend as I said before).
